In [2]:
import torch
torch.__version__

'2.4.0'

In [3]:
# Scalar
# A scalar is a single number and in tensor-speak it's a zero dimension tensor.
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
# dimension

scalar.ndim

0

In [5]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [6]:
# Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim
#We can tell the number of dimensions a tensor in PyTorch has by the number of 
#square brackets on the outside ([) and we only need to count one side.

1

In [8]:
#check the shape of vector
vector.shape

# The above returns torch.Size([2]) which means our vector has a shape of [2]
# This is because of the two elements we placed inside the square brackets ([7, 7])

torch.Size([2])

In [9]:
#matrix
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [11]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
#check the number of dimensions for tensor
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
exp_1=torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
exp_1

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [15]:
exp_1.shape

torch.Size([3, 2, 2])

In [16]:
exp_1.ndim

3

In [17]:
# Creating a tensor of random values of size (3,4)
Rtensor=torch.rand(size=(3,4))
Rtensor

tensor([[0.6173, 0.7445, 0.4083, 0.5966],
        [0.4451, 0.1118, 0.5365, 0.7153],
        [0.7781, 0.5235, 0.3661, 0.5666]])

In [18]:
# Checking the datatype of tensor
Rtensor.dtype

torch.float32

In [19]:
# Creating a random tensor of size 224,224,3

random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
random_image_size_tensor

tensor([[[0.6325, 0.3203, 0.8186],
         [0.8695, 0.7795, 0.4215],
         [0.3684, 0.8606, 0.0573],
         ...,
         [0.4696, 0.0943, 0.5797],
         [0.6321, 0.4677, 0.3220],
         [0.5800, 0.6682, 0.8499]],

        [[0.2137, 0.2329, 0.1832],
         [0.6384, 0.7810, 0.3955],
         [0.9037, 0.0672, 0.3947],
         ...,
         [0.7843, 0.8987, 0.2134],
         [0.0660, 0.9236, 0.3556],
         [0.0203, 0.3414, 0.3702]],

        [[0.2891, 0.5844, 0.5615],
         [0.2002, 0.5964, 0.7999],
         [0.2548, 0.2493, 0.1057],
         ...,
         [0.7989, 0.4578, 0.0637],
         [0.6536, 0.9387, 0.8601],
         [0.7239, 0.9618, 0.0660]],

        ...,

        [[0.7060, 0.2180, 0.5674],
         [0.0422, 0.3959, 0.2620],
         [0.0235, 0.0500, 0.1191],
         ...,
         [0.3198, 0.4125, 0.6476],
         [0.3601, 0.2236, 0.6553],
         [0.0218, 0.3698, 0.0935]],

        [[0.4391, 0.0756, 0.6400],
         [0.1714, 0.5850, 0.8443],
         [0.

In [21]:
# Creating a zeros tensor 

zeros=torch.zeros(size=(3,3))
zeros, zeros.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32)

In [22]:
# Creating a ones tensor

Ones=torch.ones(size=(3,3))
Ones, Ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

In [23]:
# A range of tensor 

zero_to_ten= torch.arange(start=0,end=10,step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# Creating tensor like others

tensor_like=torch.ones_like(input=zero_to_ten)
tensor_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
tensor_like0=torch.zeros_like(input=zero_to_ten)
tensor_like0

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
# Details of a default tensor

float_32_tensor=torch.tensor([2,3,1], dtype=None, device=None, requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.int64, device(type='cpu'))

Tensor datatypes
There are many different tensor datatypes available in PyTorch.

Some are specific for CPU and some are better for GPU.

Getting to know which is which can take some time.

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

Note: An integer is a flat round number like 7 whereas a float has a decimal 7.0.

The reason for all of these is to do with precision in computing.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).


In [27]:
# Creating a tensor of a particular datatype

torch_16_tensor=torch.tensor([1,2,3], dtype=torch.float32)
torch_16_tensor

tensor([1., 2., 3.])

In [28]:
# Details of a random tensor
rtensor=torch.rand(size=(3,3))
print(rtensor)
print("\n")
print(rtensor.dtype,": Data type of rtensor")
print(rtensor.device,": System used by rtensor")
print(rtensor.shape,": Shape of rtensor")

tensor([[0.8483, 0.8845, 0.1670],
        [0.3983, 0.2410, 0.5876],
        [0.8765, 0.8623, 0.8734]])


torch.float32 : Data type of rtensor
cpu : System used by rtensor
torch.Size([3, 3]) : Shape of rtensor


# Manipulating Tensors

In [29]:
# Creating a tensor and adding a value to it

artpol=torch.tensor([1,2,3])
print(artpol)

tensor([1, 2, 3])


In [30]:
print(artpol+10)
print(artpol*10)

tensor([11, 12, 13])
tensor([10, 20, 30])


In [31]:
# Subtract and Reassign

artpol=artpol-10
print(artpol)

tensor([-9, -8, -7])


In [32]:
# Add and reassign a tensor

artpol=artpol+10
print(artpol)

tensor([1, 2, 3])


In [33]:
# Using torch.multiply function 

torch.multiply(artpol,10)  # This is an elementwise operation

tensor([10, 20, 30])

In [34]:
# Using torch.add function

torch.add(artpol,10)    

tensor([11, 12, 13])

In [35]:
# Element wise multiplication

print(artpol,"*",artpol)   # OR torch.multiply(artpol,artpol)        
print("equals",artpol*artpol) 

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals tensor([1, 4, 9])


In [36]:
# Elementwise multiplication vs Matrix multipplication

telsat=torch.tensor([1,2,3,4])
print("Element-wise multiplication: ")
print(torch.multiply(telsat,telsat),"\n")

print("Matrix multiplication: ")
print(torch.matmul(telsat,telsat)) # OR # Can also use the "@" symbol for matrix multiplication, though not recommended telsat@telsat



Element-wise multiplication: 
tensor([ 1,  4,  9, 16]) 

Matrix multiplication: 
tensor(30)


In [37]:
# Time complexity for same output but different methods

import timeit

# Define the code to be tested as a string
code = """
value = torch.tensor(0.0)
for i in range(len(telsat)):
    value = value + telsat[i] * telsat[i]
"""

# Define the setup code to initialize the test data
setup = """
import torch
telsat = torch.arange(1000.0)
"""

# Time the execution of the test code
execution_time = timeit.timeit(stmt=code, setup=setup, number=1000)
print(f"Execution time for 1000 iterations: {execution_time} seconds")

Execution time for 1000 iterations: 22.181938000023365 seconds


In [38]:
import timeit

# Define the code to be tested as a string
code = """
telsat*telsat
"""

# Define the setup code to initialize the test data
setup = """
import torch
telsat = torch.arange(1000.0)
"""

# Time the execution of the test code
execution_time = timeit.timeit(stmt=code, setup=setup, number=1000)
print(f"Execution time for 1000 iterations: {execution_time} seconds")

Execution time for 1000 iterations: 0.010116800083778799 seconds


In [39]:
# Multiplication of two matrix

tensor_A=torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.float32)
tensor_B=torch.tensor([[4,6],[9,7],[1,9]],dtype=torch.float32)

print("tensor_A \n",tensor_A, tensor_A.shape,"\ntensor_B\n",tensor_B, tensor_B.shape)

tensor_A 
 tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) torch.Size([3, 2]) 
tensor_B
 tensor([[4., 6.],
        [9., 7.],
        [1., 9.]]) torch.Size([3, 2])


In [40]:
print("tensor_A \n",tensor_A, tensor_A.shape,"\ntensor_B.T\n",tensor_B.T, tensor_B.T.shape)

tensor_A 
 tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) torch.Size([3, 2]) 
tensor_B.T
 tensor([[4., 9., 1.],
        [6., 7., 9.]]) torch.Size([2, 3])


In [41]:
#We can also use torch.mm() which is a short for torch.matmul()
print("tensor_A x tensor_B:\n")
print(torch.matmul(tensor_A,tensor_B.T))

tensor_A x tensor_B:

tensor([[16., 23., 19.],
        [36., 55., 39.],
        [56., 87., 59.]])


# Torch.nn.Linear() module

The torch.nn.Linear() module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input x and a weights matrix A.

y=x⋅AT+b


x is the input to the layer (deep learning is a stack of layers like torch.nn.Linear() and others on top of each other).
A is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "T", that's because the weights matrix gets transposed).
Note: You might also often see W or another letter like X used to showcase the weights matrix.
b is the bias term used to slightly offset the weights and inputs.
y is the output (a manipulation of the input in the hopes to discover patterns in it).
This is a linear function (you may have seen something like y=mx+b,
in high school or elsewhere), and can be used to draw a straight line!

In [42]:
linear=torch.nn.Linear(in_features=3 # in_features = matches inner dimension of input  
                        ,out_features=2) # out_features = describes outer value
tensor_X=torch.tensor([[2,4,4],[1,5,8]],dtype=torch.float32)
x=tensor_X
output=linear(x)
print('Output:\n', output)

print("\nBias: ", linear.bias)     # has shape of 3
print("\nWeights: ", linear.weight) # transpose of this is multiplied with the input matrix to get x.(A.T)

Output:
 tensor([[3.9151, 0.9199],
        [5.1429, 1.7601]], grad_fn=<AddmmBackward0>)

Bias:  Parameter containing:
tensor([0.4981, 0.1893], requires_grad=True)

Weights:  Parameter containing:
tensor([[ 0.3806,  0.3492,  0.3148],
        [ 0.0759, -0.1124,  0.2571]], requires_grad=True)


In [43]:
# Finding minimum, maximum, mean, sum 

rayone=torch.arange(start=0, end=50, step=5)
print(rayone)

print('Minimum :',rayone.min())
print('Maximum :',rayone.max())
print('Mean :',rayone.type(torch.float32).mean())
print('Sum :',rayone.sum())

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])
Minimum : tensor(0)
Maximum : tensor(45)
Mean : tensor(22.5000)
Sum : tensor(225)


In [44]:
# Changing the datatype of a tensor

ceor=torch.arange(1,40,3)
print(ceor, ceor.dtype)
print('To float32 :',ceor.type(torch.float32),ceor.type(torch.float32).dtype)
print('To float16 :',ceor.type(torch.float16))

tensor([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37]) torch.int64
To float32 : tensor([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28., 31., 34., 37.]) torch.float32
To float16 : tensor([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28., 31., 34., 37.],
       dtype=torch.float16)


In [45]:
# Reshaping, stacking, squeezing and unsqueezing


ruess=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(ruess)
print("ruess.shape: ",ruess.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
ruess.shape:  torch.Size([3, 3])


In [46]:
# Reshaping

print(torch.reshape(ruess,(9,1)))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [47]:
# Viewing in different shape

print(ruess.view(1,9))

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])


In [48]:
# Stacking the tensors 
ruess_1=torch.ones_like(ruess)
x=torch.stack((ruess,ruess_1),dim=2)
print(x, x.shape, x.ndim)    

tensor([[[1, 1],
         [2, 1],
         [3, 1]],

        [[4, 1],
         [5, 1],
         [6, 1]],

        [[7, 1],
         [8, 1],
         [9, 1]]]) torch.Size([3, 3, 2]) 3


In [49]:
ruess_1=torch.ones_like(ruess)
print(torch.stack((ruess,ruess_1),dim=0))

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]])


In PyTorch, the dim argument in functions like torch.stack specifies the dimension along which the operation is performed. The value of dim determines where the new dimension is inserted in the resulting tensor.

Understanding Dimensions (dim)
dim=0: This indicates the first dimension (rows).
dim=1: This indicates the second dimension (columns).

Initialize a new tensor with an additional dimension:
The new tensor will have one more dimension than the input tensors. Since we are stacking along dim=1, 
the new shape will be (3, 2, 3). The 2 comes from the number of tensors being stacked, 
and the remaining dimensions come from the shape of the original tensors.

Concatenate along the specified dimension:
The elements from each input tensor are combined along the new dimension.

In [50]:
# torch.squeeze : Squeezes the input to remove all the dimensions with value 1

dimtor=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

print('dimtor :\n',dimtor)
print('dimtor has dimension',dimtor.ndim,'and shape', dimtor.shape,'\n')
print('torch.squeeze(dimtor)\n',torch.squeeze(dimtor))
print('torch.squeeze(dimtor).shape:',torch.squeeze(dimtor).shape)
print('torch.squeeze(dimtor).dim:',torch.squeeze(dimtor).ndim)

dimtor :
 tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
dimtor has dimension 3 and shape torch.Size([1, 3, 3]) 

torch.squeeze(dimtor)
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.squeeze(dimtor).shape: torch.Size([3, 3])
torch.squeeze(dimtor).dim: 2


In [51]:
# torch.unsqueeze : add a dimension at a specified dimensional value

woem=torch.tensor([[1,2,3],[4,5,6]]) # has 2 dimensions and shape of 2,3
print('woem: \n',woem, '\n shape',woem.shape, 'dimensions ',woem.ndim)
print('\n torch.unsqueeze(woem,dim=0):\n', torch.unsqueeze(woem,dim=0))
print('torch.unsqueeze(woem,dim=0).ndim=',torch.unsqueeze(woem,dim=0).ndim, 
      '\ntorch.unsqueeze(woem,dim=0).shape=',torch.unsqueeze(woem,dim=0).shape)

woem: 
 tensor([[1, 2, 3],
        [4, 5, 6]]) 
 shape torch.Size([2, 3]) dimensions  2

 torch.unsqueeze(woem,dim=0):
 tensor([[[1, 2, 3],
         [4, 5, 6]]])
torch.unsqueeze(woem,dim=0).ndim= 3 
torch.unsqueeze(woem,dim=0).shape= torch.Size([1, 2, 3])


In [52]:
# Permute operation: Rearranging the tensor 

tensor = torch.tensor([[[ 1,  2,  3,  4],
                        [ 5,  6,  7,  8],
                        [ 9, 10, 11, 12]],

                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]])

print("Original tensor:\n", tensor)
print("Original tensor shape:", tensor.shape)

# Permute the dimensions to (4, 2, 3)
permuted_tensor = tensor.permute(2, 0, 1) 
print("Permuted tensor:\n", permuted_tensor) # 1st dim is same to dim of orginal 2nd dim, 2nd dim is that of 0 dim of original,
                                              # 3rd dim is same as that of 1st dim of original
print("Permuted tensor shape:", permuted_tensor.shape) 

Original tensor:
 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
Original tensor shape: torch.Size([2, 3, 4])
Permuted tensor:
 tensor([[[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]],

        [[ 4,  8, 12],
         [16, 20, 24]]])
Permuted tensor shape: torch.Size([4, 2, 3])


Original Tensor:

Shape: (2, 3, 4)
Contains two 3x4 matrices.
Permuted Tensor:

Shape: (4, 2, 3)
The first dimension of size 4 corresponds to the original last dimension.
The second dimension of size 2 corresponds to the original first dimension.
The third dimension of size 3 corresponds to the original second dimension.
Use Cases
Changing Image Data Format:
Many image processing tasks require the data to be in specific formats (e.g., channels-first vs. channels-last).
torch.permute can be used to rearrange the dimensions of image tensors to match the required format.
Adjusting Tensor Shapes for Operations:
Certain operations or layers in neural networks may expect inputs with specific dimension orders.
torch.permute helps in aligning the tensor dimensions as needed.
In summary, torch.permute is a powerful tool for rearranging the dimensions of tensors, allowing you to transform the shape of your data to fit various processing requirements.

In [53]:
# Finding the index number of the maximum value in a tensor 
axor=torch.tensor([1,2,3,45,2,67,90,123,56,23,9,0,-1,45])

print(f"Index of max value is: {axor.argmax()} and the value is {axor[axor.argmax()]}")
print(f"Index of min value is: {axor.argmin()} and the value is {axor[axor.argmin()]}")

Index of max value is: 7 and the value is 123
Index of min value is: 12 and the value is -1


In [54]:
# Indexing the data from tensor

trex=torch.tensor([[[1,2,3],[3,4,5],[6,7,8]]])
print(trex)

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])


In [55]:
# Extracting a datavalue from a tensor
trex[0][1][2]

tensor(5)

In [56]:
# 
print(trex[:,:,2]) # from 1st dimension collect all, from 2nd dimension select all rows, from all rows select 2nd value 
print(trex[:,1]) # from 1st dimension select everything, select 1st row

tensor([[3, 5, 8]])
tensor([[3, 4, 5]])


In [57]:
# from numpy to tensor and vice-versa
import numpy as np

raysor=np.arange(0,10,1)
print(f"Array: {raysor}")
teray=torch.from_numpy(raysor).type(torch.float32)
print(f"Converted into a tensor: {teray, teray.dtype}")
print(f"\nTensor: {teray, teray.dtype}")
ttray=teray.numpy()
print(f"Converted to a numpy array: ",ttray)

Array: [0 1 2 3 4 5 6 7 8 9]
Converted into a tensor: (tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

Tensor: (tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)
Converted to a numpy array:  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
